#ifndef E_RESOURCE_EXPORT_H
#define E_RESOURCE_EXPORT_H

extern char _binary_shaders_model_frag_spv_end;
extern int _binary_shaders_model_frag_spv_size;
extern char _binary_shaders_model_frag_spv_start;
extern char _binary_shaders_model_vert_spv_end;
extern int _binary_shaders_model_vert_spv_size;
extern char _binary_shaders_model_vert_spv_start;
extern char _binary_shaders_model_shadow_frag_spv_end;
extern int _binary_shaders_model_shadow_frag_spv_size;
extern char _binary_shaders_model_shadow_frag_spv_start;
extern char _binary_shaders_model_shadow_vert_spv_end;
extern int _binary_shaders_model_shadow_vert_spv_size;
extern char _binary_shaders_model_shadow_vert_spv_start;


extern char _binary_shaders_text_frag_spv_end;
extern int _binary_shaders_text_frag_spv_size;
extern char _binary_shaders_text_frag_spv_start;
extern char _binary_shaders_text_vert_spv_end;
extern int _binary_shaders_text_vert_spv_size;
extern char _binary_shaders_text_vert_spv_start;

extern char _binary_shaders_quad_frag_spv_end;
extern int _binary_shaders_quad_frag_spv_size;
extern char _binary_shaders_quad_frag_spv_start;
extern char _binary_shaders_quad_frag_2_spv_end;
extern int _binary_shaders_quad_frag_2_spv_size;
extern char _binary_shaders_quad_frag_2_spv_start;
extern char _binary_shaders_quad_vert_spv_end;
extern int _binary_shaders_quad_vert_spv_size;
extern char _binary_shaders_quad_vert_spv_start;

extern char _binary_shaders_depth_frag_spv_end;
extern int _binary_shaders_depth_frag_spv_size;
extern char _binary_shaders_depth_frag_spv_start;
extern char _binary_shaders_depth_vert_spv_end;
extern int _binary_shaders_depth_vert_spv_size;
extern char _binary_shaders_depth_vert_spv_start;

extern char _binary_shaders_depth_frag_omni_spv_end;
extern int _binary_shaders_depth_frag_omni_spv_size;
extern char _binary_shaders_depth_frag_omni_spv_start;
extern char _binary_shaders_depth_vert_omni_spv_end;
extern int _binary_shaders_depth_vert_omni_spv_size;
extern char _binary_shaders_depth_vert_omni_spv_start;

extern char _binary_shaders_depth_frag_spot_spv_end;
extern int _binary_shaders_depth_frag_spot_spv_size;
extern char _binary_shaders_depth_frag_spot_spv_start;
extern char _binary_shaders_depth_vert_spot_spv_end;
extern int _binary_shaders_depth_vert_spot_spv_size;
extern char _binary_shaders_depth_vert_spot_spv_start;

extern char _binary_shaders_terrain_frag_spv_end;
extern int _binary_shaders_terrain_frag_spv_size;
extern char _binary_shaders_terrain_frag_spv_start;
extern char _binary_shaders_terrain_vert_spv_end;
extern int _binary_shaders_terrain_vert_spv_size;
extern char _binary_shaders_terrain_vert_spv_start;

extern char _binary_shaders_terrain_frag_2_spv_end;
extern int _binary_shaders_terrain_frag_2_spv_size;
extern char _binary_shaders_terrain_frag_2_spv_start;
extern char _binary_shaders_terrain_vert_2_spv_end;
extern int _binary_shaders_terrain_vert_2_spv_size;
extern char _binary_shaders_terrain_vert_2_spv_start;

extern char _binary_shaders_texture_frag_spv_end;
extern int _binary_shaders_texture_frag_spv_size;
extern char _binary_shaders_texture_frag_spv_start;
extern char _binary_shaders_texture_vert_spv_end;
extern int _binary_shaders_texture_vert_spv_size;
extern char _binary_shaders_texture_vert_spv_start;

extern char _binary_shaders_sky_sky_frag_spv_end;
extern int _binary_shaders_sky_sky_frag_spv_size;
extern char _binary_shaders_sky_sky_frag_spv_start;
extern char _binary_shaders_sky_sky_vert_spv_end;
extern int _binary_shaders_sky_sky_vert_spv_size;
extern char _binary_shaders_sky_sky_vert_spv_start;

extern char _binary_shaders_sky_stars_frag_spv_end;
extern int _binary_shaders_sky_stars_frag_spv_size;
extern char _binary_shaders_sky_stars_frag_spv_start;
extern char _binary_shaders_sky_stars_vert_spv_end;
extern int _binary_shaders_sky_stars_vert_spv_size;
extern char _binary_shaders_sky_stars_vert_spv_start;

extern char _binary_shaders_sky_atmospheric_frag_spv_end;
extern int _binary_shaders_sky_atmospheric_frag_spv_size;
extern char _binary_shaders_sky_atmospheric_frag_spv_start;
extern char _binary_shaders_sky_atmospheric_vert_spv_end;
extern int _binary_shaders_sky_atmospheric_vert_spv_size;
extern char _binary_shaders_sky_atmospheric_vert_spv_start;

extern char _binary_shaders_sprite_frag_spv_end;
extern int _binary_shaders_sprite_frag_spv_size;
extern char _binary_shaders_sprite_frag_spv_start;
extern char _binary_shaders_sprite_vert_spv_end;
extern int _binary_shaders_sprite_vert_spv_size;
extern char _binary_shaders_sprite_vert_spv_start;

extern char _binary_shaders_particle_frag2D_spv_end;
extern int _binary_shaders_particle_frag2D_spv_size;
extern char _binary_shaders_particle_frag2D_spv_start;
extern char _binary_shaders_particle_vert2D_spv_end;
extern int _binary_shaders_particle_vert2D_spv_size;
extern char _binary_shaders_particle_vert2D_spv_start;

extern char _binary_shaders_particle_frag3D_spv_end;
extern int _binary_shaders_particle_frag3D_spv_size;
extern char _binary_shaders_particle_frag3D_spv_start;
extern char _binary_shaders_particle_vert3D_spv_end;
extern int _binary_shaders_particle_vert3D_spv_size;
extern char _binary_shaders_particle_vert3D_spv_start;

extern char _binary_shaders_3d_object_frag_spv_end;
extern int _binary_shaders_3d_object_frag_spv_size;
extern char _binary_shaders_3d_object_frag_spv_start;
extern char _binary_shaders_3d_object_vert_spv_end;
extern int _binary_shaders_3d_object_vert_spv_size;
extern char _binary_shaders_3d_object_vert_spv_start;
extern char _binary_shaders_3d_object_shadow_frag_spv_end;
extern int _binary_shaders_3d_object_shadow_frag_spv_size;
extern char _binary_shaders_3d_object_shadow_frag_spv_start;
extern char _binary_shaders_3d_object_shadow_vert_spv_end;
extern int _binary_shaders_3d_object_shadow_vert_spv_size;
extern char _binary_shaders_3d_object_shadow_vert_spv_start;

extern char _binary_shaders_3d_object_line_frag_spv_end;
extern int _binary_shaders_3d_object_line_frag_spv_size;
extern char _binary_shaders_3d_object_line_frag_spv_start;
extern char _binary_shaders_3d_object_line_vert_spv_end;
extern int _binary_shaders_3d_object_line_vert_spv_size;
extern char _binary_shaders_3d_object_line_vert_spv_start;

extern char _binary_shaders_gui_widget_frag_spv_end;
extern int _binary_shaders_gui_widget_frag_spv_size;
extern char _binary_shaders_gui_widget_frag_spv_start;
extern char _binary_shaders_gui_widget_vert_spv_end;
extern int _binary_shaders_gui_widget_vert_spv_size;
extern char _binary_shaders_gui_widget_vert_spv_start;

extern char _binary_shaders_gui_painter_frag_spv_end;
extern int _binary_shaders_gui_painter_frag_spv_size;
extern char _binary_shaders_gui_painter_frag_spv_start;
extern char _binary_shaders_gui_painter_vert_spv_end;
extern int _binary_shaders_gui_painter_vert_spv_size;
extern char _binary_shaders_gui_painter_vert_spv_start;

extern char _binary_shaders_gui_widget_window_frag_spv_end;
extern int _binary_shaders_gui_widget_window_frag_spv_size;
extern char _binary_shaders_gui_widget_window_frag_spv_start;
extern char _binary_shaders_gui_widget_window_vert_spv_end;
extern int _binary_shaders_gui_widget_window_vert_spv_size;
extern char _binary_shaders_gui_widget_window_vert_spv_start;

extern char _binary_fonts_null_normal_otf_end;
extern int _binary_fonts_null_normal_otf_size;
extern char _binary_fonts_null_normal_otf_start;

extern char _binary_fonts_fantazer_normal_ttf_end;
extern int _binary_fonts_fantazer_normal_ttf_size;
extern char _binary_fonts_fantazer_normal_ttf_start;

extern char _binary_fonts_RobotoBlack_ttf_end;
extern int _binary_fonts_RobotoBlack_ttf_size;
extern char _binary_fonts_RobotoBlack_ttf_start;

extern char _binary_fonts_TenorSans_ttf_end;
extern int _binary_fonts_TenorSans_ttf_size;
extern char _binary_fonts_TenorSans_ttf_start;

#endif // E_RESOURCE_EXPORT_H
